"""empty message

Revision ID: 905ddbce1003
Revises: 5d7490ba30a0
Create Date: 2021-08-23 21:00:15.835091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ddbce1003'
down_revision = '5d7490ba30a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorite', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'vehicle_id')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
