"""empty message

Revision ID: c8cf7246717f
Revises: a9d8e645dbbb
Create Date: 2021-08-24 03:28:23.364835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8cf7246717f'
down_revision = 'a9d8e645dbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('climate', sa.String(length=150), nullable=False))
    op.add_column('planet', sa.Column('diameter', sa.String(length=150), nullable=False))
    op.add_column('planet', sa.Column('orbital_period', sa.String(length=150), nullable=False))
    op.drop_column('planet', 'terrain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('terrain', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'climate')
    # ### end Alembic commands ###
